### ISSUE TITLE
Docker container for day 2 of Coco2019

### ISSUE THREAD

**Issue by djarecka** [nipype/coco2019-training#1]
let's collect all software we will need to install in the Docker container for day 2.

We can try to create it by the end of the teaching day to have time to test it tonight. I believe we will have enough time tomorrow morning to ask people to pull.

**Comment by effigies** [comment]
I need `conda` (with `pip`) and `git`. I think that's it.

**Comment by satra** [comment]
let's also make sure the user as sudo rights.

**Comment by djarecka** [comment]
`git-annex` and `datalad` just in case

**Comment by kaczmarj** [comment]
Here is the neurodocker command at this point:

```bash
docker run --rm -it kaczmarj/neurodocker:master generate docker \
  --base=neurodebian:stretch-non-free \
  --pkg-manager=apt \
  --install datalad fsl git git-annex-standalone \
  --install emacs nano sudo vim \
  --user=neuro \
  --miniconda \
        use_env=base \
        conda_install='python=3.6 pytest traits numpy nomkl' \
        pip_install='nipype' \
  --user=root \
  --run 'usermod -aG sudo neuro && passwd neuro --delete' \
  --user=neuro
```

available on dockerhub at `kaczmarj/coco2019:day2`.

**Comment by TimVanMourik** [comment]
No installation requirements from my side. Kinda the point of a web app 😎

**Comment by effigies** [comment]
I think this is safe to close...
